#!/usr/bin/env node
"use strict";

/*
 * Prepares the framework theme-build harness in a gitignored tmp folder.
 *
 * The harness is a minimal UI5 application project that depends on *all* SAPUI5
 * framework libraries, so `ui5 build` (via @ui5/builder → less-openui5) can
 * build every theme. Nothing about the harness is checked in: this script
 * generates it on demand into test/integration/tmp/framework-theme-build/.
 *
 * The framework library list is derived from @sapui5/distribution-metadata.
 * Rather than declaring that package as a dependency (which would pull in a
 * lockfile), we install it on demand into an isolated tmp project via the npm
 * CLI — the same pattern OpenUI5 uses in lib/theming-base-content/update.js.
 *
 *   node scripts/prepare.js [version]
 *
 *   version  @sapui5/distribution-metadata version (dist-tag or exact).
 *            Default: "latest".
 */

const path = require("node:path");
const {promisify} = require("node:util");
const {readFile, writeFile, mkdir, rm, stat} = require("node:fs/promises");
const {execFile} = require("node:child_process");
const execFileAsync = promisify(execFile);

const METADATA_PKG = "@sapui5/distribution-metadata";

// This file lives at <root>/test/integration/framework-theme-build/scripts/.
const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");
const integrationDir = path.join(repoRoot, "test", "integration");
const tmpDir = path.join(integrationDir, "tmp");
// Isolated project used only to fetch the metadata package.
const metadataProjectDir = path.join(tmpDir, "metadata");
// The generated harness that `ui5 build` runs against.
const harnessDir = path.join(tmpDir, "framework-theme-build");

function relativePath(p) {
	return path.relative(process.cwd(), p);
}

async function exists(filePath) {
	try {
		await stat(filePath);
		return true;
	} catch (err) {
		if (err.code === "ENOENT") {
			return false;
		}
		throw err;
	}
}

async function readJson(filePath) {
	return JSON.parse(await readFile(filePath, {encoding: "utf-8"}));
}

// Install @sapui5/distribution-metadata@<version> into an isolated, empty
// project via the npm CLI and return the path to its unpacked package dir.
// "npm install" needs a package.json to act as the project root; without one
// npm would walk up and install into the surrounding workspace. --no-package-lock
// keeps this lockfile-free.
async function installMetadata(version) {
	const npmSpec = `${METADATA_PKG}@${version}`;
	console.log(`Installing ${npmSpec} into ${relativePath(metadataProjectDir)} ...`);

	await mkdir(metadataProjectDir, {recursive: true});
	await writeFile(
		path.join(metadataProjectDir, "package.json"),
		JSON.stringify({name: "distribution-metadata-download", version: "0.0.0", private: true})
	);

	await execFileAsync(
		"npm",
		["install", npmSpec, "--no-save", "--no-audit", "--no-fund", "--no-package-lock", "--ignore-scripts"],
		{cwd: metadataProjectDir}
	);

	return path.join(metadataProjectDir, "node_modules", METADATA_PKG);
}

function renderUi5Yaml(version, libraryNames) {
	const lines = [];
	lines.push("# Generated by scripts/prepare.js from @sapui5/distribution-metadata.");
	lines.push("# Do not edit by hand — re-run `npm run theme-build:prepare` to regenerate.");
	lines.push('specVersion: "4.0"');
	lines.push("metadata:");
	lines.push("  name: sapui5.framework.build");
	lines.push("type: application");
	lines.push("framework:");
	lines.push("  name: SAPUI5");
	lines.push(`  version: "${version}"`);
	lines.push("  libraries:");
	for (const name of libraryNames) {
		lines.push(`    - name: ${name}`);
	}
	return lines.join("\n") + "\n";
}

function renderPackageJson() {
	return JSON.stringify({
		name: "framework-theme-build",
		version: "1.0.0",
		private: true,
		description: "Generated integration test harness (do not edit — see scripts/prepare.js).",
	}, null, 2) + "\n";
}

function renderManifest(version) {
	return JSON.stringify({
		_version: "1.65.0",
		"sap.app": {
			id: "sapui5.framework.build",
			type: "application",
			applicationVersion: {version: "1.0.0"},
			title: "SAPUI5 Framework Build",
		},
		"sap.ui5": {
			dependencies: {minUI5Version: version},
		},
	}, null, 2) + "\n";
}

async function main() {
	const version = process.argv[2] || "latest";

	console.log(`\nCleaning tmp folder ${relativePath(tmpDir)} ...\n`);
	await rm(tmpDir, {recursive: true, force: true});

	const metadataDir = await installMetadata(version);

	const metadata = await readJson(path.join(metadataDir, "metadata.json"));
	const metadataPkg = await readJson(path.join(metadataDir, "package.json"));
	const resolvedVersion = metadataPkg.version;

	const libraryNames = Object.keys(metadata.libraries).sort();
	if (libraryNames.length === 0) {
		throw new Error(`No libraries found in ${METADATA_PKG}@${resolvedVersion}`);
	}

	console.log(`\nGenerating harness in ${relativePath(harnessDir)} ...`);
	await mkdir(path.join(harnessDir, "webapp"), {recursive: true});

	await writeFile(path.join(harnessDir, "ui5.yaml"), renderUi5Yaml(resolvedVersion, libraryNames));
	await writeFile(path.join(harnessDir, "package.json"), renderPackageJson());
	await writeFile(path.join(harnessDir, "webapp", "manifest.json"), renderManifest(resolvedVersion));

	// Sanity check: the harness dir must exist for the build scripts.
	if (!(await exists(path.join(harnessDir, "ui5.yaml")))) {
		throw new Error(`Failed to write harness to ${harnessDir}`);
	}

	console.log(`\nPrepared harness:`);
	console.log(`  framework:  SAPUI5 ${resolvedVersion}`);
	console.log(`  libraries:  ${libraryNames.length}`);
	console.log(`  location:   ${relativePath(harnessDir)}`);
	console.log(`\nNext: npm run theme-build:baseline  &&  npm run theme-build:compare-build  &&  npm run theme-build:compare`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
